backend:
  name: git-gateway

media_folder: "site/static/img" # Folder where user uploaded files should go
public_folder: "img"

collections: # A list of collections the CMS should be able to edit
  - name: "pages"
    label: "Pages"
    files:
      - file: "site/content/_index.md"
        label: "Home Page"
        name: "home"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Body, name: body, widget: markdown}
      - file: "site/content/about/_index.md"
        label: "About/FAQ"
        name: "about"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Description, name: description, widget: markdown}
          - label: "FAQ Entries"
	    name: "entries"
	    widget: "list"
	    fields:
	      - {label: Question, name: question, widget: string}
	      - {label: Answer, name: answer, widget: markdown}
      - file: "site/content/access/_index.md"
        label: "Access the Database"
        name: "access"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Body, name: body, widget: markdown}
      - file: "site/content/contact_index.md"
        label: "Contact Us"
        name: "contact"
        fields:
          - {label: Title, name: title, widget: string}
      - file: "site/content/groups/_index.md"
        label: "Community Groups"
        name: "groups"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Description, name: description, widget: markdown}
          - label: "Groups"
	    name: "groups"
	    widget: "list"
	    fields:
	      - {label: Group, name: group, widget: string}
	      - {label: Location, name: location, widget: string}
	      - {label: Organizers, name: organizers, widget: markdown}
	      - {label: Contacts, name: contacts, widget: markdown}
      - file: "site/content/join/_index.md"
        label: "Join Us"
        name: "join"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Body, name: body, widget: markdown}
      - file: "site/content/public-db/_index.md"
        label: "Public Database"
        name: "public-db"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Body, name: body, widget: markdown}
      - file: "site/content/successes/_index.md"
        label: "Successes"
        name: "successes"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Access list description, name: haveAccessDescription, widget: string}
	  - label: "Access list"
	    name: "haveAccess"
	    widget: "list"
	    fields:
	      - {label: "Name", name: name, widget: string}
          - {label: Regional access list description, name: regionalAccessDescription, widget: string}
	  - label: "Regional access list"
	    name: "regionalAccess"
	    widget: "list"
	    fields:
	      - {label: "Name", name: name, widget: string}
          - {label: Regional opt-in list description, name: regionalOptinDescription, widget: string}
	  - label: "Regional opt-in list"
	    name: "regionalOptin"
	    widget: "list"
	    fields:
	      - {label: "Name", name: name, widget: string}
      - file: "site/content/team/_index.md"
        label: "Meet the Team"
        name: "team"
        fields:
          - {label: Title, name: title, widget: string}
          - label: "People"
	    name: "people"
	    widget: "list"
	    fields:
	      - {label: "Name", name: name, widget: string}
	      - {label: "Affiliation", name: affiliation, widget: string}
